# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import MusicService_pb2 as protos_dot_MusicService__pb2


class MusicStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.requestMusic = channel.unary_unary(
                '/GRPC.Music/requestMusic',
                request_serializer=protos_dot_MusicService__pb2.MusicRequest.SerializeToString,
                response_deserializer=protos_dot_MusicService__pb2.MusicResponse.FromString,
                )
        self.addMusic = channel.stream_unary(
                '/GRPC.Music/addMusic',
                request_serializer=protos_dot_MusicService__pb2.AddMusicRequest.SerializeToString,
                response_deserializer=protos_dot_MusicService__pb2.AddMusicResponse.FromString,
                )
        self.removeMusic = channel.unary_unary(
                '/GRPC.Music/removeMusic',
                request_serializer=protos_dot_MusicService__pb2.RemoveMusicRequest.SerializeToString,
                response_deserializer=protos_dot_MusicService__pb2.RemoveMusicResponse.FromString,
                )


class MusicServicer(object):
    """Missing associated documentation comment in .proto file."""

    def requestMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addMusic(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'requestMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.requestMusic,
                    request_deserializer=protos_dot_MusicService__pb2.MusicRequest.FromString,
                    response_serializer=protos_dot_MusicService__pb2.MusicResponse.SerializeToString,
            ),
            'addMusic': grpc.stream_unary_rpc_method_handler(
                    servicer.addMusic,
                    request_deserializer=protos_dot_MusicService__pb2.AddMusicRequest.FromString,
                    response_serializer=protos_dot_MusicService__pb2.AddMusicResponse.SerializeToString,
            ),
            'removeMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.removeMusic,
                    request_deserializer=protos_dot_MusicService__pb2.RemoveMusicRequest.FromString,
                    response_serializer=protos_dot_MusicService__pb2.RemoveMusicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPC.Music', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Music(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def requestMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPC.Music/requestMusic',
            protos_dot_MusicService__pb2.MusicRequest.SerializeToString,
            protos_dot_MusicService__pb2.MusicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addMusic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/GRPC.Music/addMusic',
            protos_dot_MusicService__pb2.AddMusicRequest.SerializeToString,
            protos_dot_MusicService__pb2.AddMusicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def removeMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPC.Music/removeMusic',
            protos_dot_MusicService__pb2.RemoveMusicRequest.SerializeToString,
            protos_dot_MusicService__pb2.RemoveMusicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
