# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/MusicService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/MusicService.proto\x12\x04GRPC\"\x1c\n\x0cMusicRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"/\n\x08MetaData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\textension\x18\x02 \x01(\t\"V\n\x0f\x41\x64\x64MusicRequest\x12\"\n\x08metadata\x18\x01 \x01(\x0b\x32\x0e.GRPC.MetaDataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\"\n\x12RemoveMusicRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x1c\n\rMusicResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\"/\n\x10\x41\x64\x64MusicResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03url\x18\x02 \x01(\t\"%\n\x13RemoveMusicResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xc7\x01\n\x05Music\x12\x39\n\x0crequestMusic\x12\x12.GRPC.MusicRequest\x1a\x13.GRPC.MusicResponse\"\x00\x12=\n\x08\x61\x64\x64Music\x12\x15.GRPC.AddMusicRequest\x1a\x16.GRPC.AddMusicResponse\"\x00(\x01\x12\x44\n\x0bremoveMusic\x12\x18.GRPC.RemoveMusicRequest\x1a\x19.GRPC.RemoveMusicResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.MusicService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSICREQUEST._serialized_start=35
  _MUSICREQUEST._serialized_end=63
  _METADATA._serialized_start=65
  _METADATA._serialized_end=112
  _ADDMUSICREQUEST._serialized_start=114
  _ADDMUSICREQUEST._serialized_end=200
  _REMOVEMUSICREQUEST._serialized_start=202
  _REMOVEMUSICREQUEST._serialized_end=236
  _MUSICRESPONSE._serialized_start=238
  _MUSICRESPONSE._serialized_end=266
  _ADDMUSICRESPONSE._serialized_start=268
  _ADDMUSICRESPONSE._serialized_end=315
  _REMOVEMUSICRESPONSE._serialized_start=317
  _REMOVEMUSICRESPONSE._serialized_end=354
  _MUSIC._serialized_start=357
  _MUSIC._serialized_end=556
# @@protoc_insertion_point(module_scope)
